# Generated by Django 6.1.1 on 2026-09-19 20:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('hire_date', models.DateField(blank=True, default=datetime.date.today)),
                ('probation_start', models.DateField(blank=True, null=True)),
                ('probation_end', models.DateField(blank=True, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resigned', 'Resigned'), ('terminated', 'Terminated')], default='Inactive', max_length=20)),
                ('department', models.ForeignKey(db_column='department_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr_core.department')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employees',
            },
        ),
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='Inactive', max_length=20)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='hr_core.employee')),
            ],
            options={
                'db_table': 'bank_accounts',
            },
        ),
    ]
