# Generated by Django 6.1.1 on 2026-09-19 20:38

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_core', '0001_initial'),
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvancePolicy',
            fields=[
                ('policy_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('requests_per_month', models.IntegerField(default=1)),
                ('probation_allowed', models.BooleanField(default=False)),
                ('fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'db_table': 'advance_policies',
            },
        ),
        migrations.CreateModel(
            name='AdvanceRequest',
            fields=[
                ('advance_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('request_date', models.DateField(default=datetime.date.today, editable=False)),
                ('reason', models.TextField(blank=True, null=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='hr_core.employee')),
                ('payroll', models.ForeignKey(blank=True, db_column='payroll_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='payroll.payroll')),
                ('policy', models.ForeignKey(db_column='policy_id', on_delete=django.db.models.deletion.PROTECT, to='advances.advancepolicy')),
            ],
            options={
                'db_table': 'advance_requests',
            },
        ),
    ]
