# Generated by Django 6.1.1 on 2026-09-19 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('salary_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('basic_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=50)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='hr_core.employee')),
            ],
            options={
                'db_table': 'salary',
            },
        ),
        migrations.CreateModel(
            name='Wage',
            fields=[
                ('wage_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('wage_date', models.DateField()),
                ('hours_worked', models.DecimalField(decimal_places=2, max_digits=5)),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='hr_core.employee')),
            ],
            options={
                'db_table': 'wages',
            },
        ),
        migrations.CreateModel(
            name='Payroll',
            fields=[
                ('payroll_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payroll_month', models.DateField()),
                ('total_base_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('total_wages', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('allowances', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('admin_fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('gross_salary', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('total_deductions', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_pay', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('pay_date', models.DateField()),
                ('status', models.CharField(default='CALCULATED', max_length=50)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payrolls', to='hr_core.bankaccount')),
                ('employee', models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='hr_core.employee')),
            ],
            options={
                'db_table': 'payrolls',
                'constraints': [models.UniqueConstraint(fields=('employee', 'payroll_month'), name='unique_employee_payroll_month')],
            },
        ),
    ]
